/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaConversorMoeda.java
 *
 * Created on 24/11/2011, 21:34:51
 */
package lista08;

import java.awt.Color;

/**
 *
 * @author Afonso
 */
public class JanelaConversorMoeda extends javax.swing.JFrame {

    /** Creates new form JanelaConversorMoeda */
    public JanelaConversorMoeda() {
        initComponents();
    }

    private void converterParaDolar() throws NumberFormatException {
        double real = Double.valueOf(TextField_reais.getText());
        double dolar = ConversorMoeda.converteParaDolar(real);
        TextField_dolares.setText(String.valueOf(dolar));
    }

    private void converterParaReal() throws NumberFormatException {
        double dolar = Double.valueOf(TextField_dolares.getText());
        double real = ConversorMoeda.converteParaReal(dolar);
        TextField_reais.setText(String.valueOf(real));
        
        if (real >= 100)
        {
            TextField_reais.setBackground(Color.BLUE);
        } else {
            TextField_reais.setBackground(Color.red);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConversorMoeda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextField_reais = new javax.swing.JTextField();
        TextField_dolares = new javax.swing.JTextField();
        Button_reais = new javax.swing.JButton();
        Button_dolares = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Moeda");

        jPanelConversorMoeda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("valor em reais:");

        jLabel2.setText("valor em dólares:");

        TextField_reais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_reaisActionPerformed(evt);
            }
        });
        TextField_reais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_reaisFocusLost(evt);
            }
        });

        TextField_dolares.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextField_dolaresFocusLost(evt);
            }
        });

        Button_reais.setText("converter para dólares");
        Button_reais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_reaisActionPerformed(evt);
            }
        });

        Button_dolares.setText("converter para reais");
        Button_dolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_dolaresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConversorMoedaLayout = new javax.swing.GroupLayout(jPanelConversorMoeda);
        jPanelConversorMoeda.setLayout(jPanelConversorMoedaLayout);
        jPanelConversorMoedaLayout.setHorizontalGroup(
            jPanelConversorMoedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConversorMoedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConversorMoedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConversorMoedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextField_reais, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_dolares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConversorMoedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_dolares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_reais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelConversorMoedaLayout.setVerticalGroup(
            jPanelConversorMoedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConversorMoedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConversorMoedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextField_reais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_reais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConversorMoedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_dolares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_dolares))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConversorMoeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConversorMoeda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_reaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_reaisActionPerformed
        converterParaDolar();
    }//GEN-LAST:event_Button_reaisActionPerformed

    private void Button_dolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_dolaresActionPerformed
        converterParaReal();
    }//GEN-LAST:event_Button_dolaresActionPerformed

    private void TextField_reaisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_reaisFocusLost
        converterParaDolar();
    }//GEN-LAST:event_TextField_reaisFocusLost

    private void TextField_dolaresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextField_dolaresFocusLost
       converterParaReal();
    }//GEN-LAST:event_TextField_dolaresFocusLost

    private void TextField_reaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_reaisActionPerformed
       
    }//GEN-LAST:event_TextField_reaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaConversorMoeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaConversorMoeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaConversorMoeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaConversorMoeda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JanelaConversorMoeda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_dolares;
    private javax.swing.JButton Button_reais;
    private javax.swing.JTextField TextField_dolares;
    private javax.swing.JTextField TextField_reais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelConversorMoeda;
    // End of variables declaration//GEN-END:variables
}
